# Generated by Django 6.0.6 on 2026-06-24 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant_location',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_restaurant': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='delivery.location'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_location',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_restaurant': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_orders', to='delivery.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_MERCHANT', 'Pending Merchant Approval'), ('PREPARING', 'Preparing'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('PENDING_COURIER', 'Pending Courier'), ('ACCEPTED', 'Accepted'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING_MERCHANT', max_length=20),
        ),
    ]
